/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Agency {
  agency_email: string | null;
  agency_fare_url: string | null;
  agency_id: string | null;
  agency_lang: string | null;
  agency_name: string;
  agency_phone: string | null;
  agency_timezone: string;
  agency_url: string;
  cemv_support: number | null;
}

export interface Areas {
  area_id: string;
  area_name: string | null;
}

export interface Attributions {
  agency_id: string | null;
  attribution_email: string | null;
  attribution_id: string | null;
  attribution_phone: string | null;
  attribution_url: string | null;
  is_authority: number | null;
  is_operator: number | null;
  is_producer: number | null;
  organization_name: string;
  route_id: string | null;
  trip_id: string | null;
}

export interface BoardAlight {
  alightings: number | null;
  bike_alightings: number | null;
  bike_boardings: number | null;
  boardings: number | null;
  current_load: number | null;
  load_count: number | null;
  load_type: number | null;
  rack_down: number | null;
  ramp_alightings: number | null;
  ramp_boardings: number | null;
  ramp_used: number | null;
  record_use: number;
  schedule_relationship: number | null;
  service_arrival_time: string | null;
  service_date: string | null;
  service_departure_time: string | null;
  source: number | null;
  stop_id: string;
  stop_sequence: number;
  trip_id: string;
}

export interface BookingRules {
  booking_rule_id: string | null;
  booking_type: number;
  booking_url: string | null;
  drop_off_message: string | null;
  info_url: string | null;
  message: string | null;
  phone_number: string | null;
  pickup_message: string | null;
  prior_notice_duration_max: number | null;
  prior_notice_duration_min: number | null;
  prior_notice_last_day: number | null;
  prior_notice_last_time: string | null;
  prior_notice_service_id: string | null;
  prior_notice_start_day: number | null;
  prior_notice_start_time: string | null;
}

export interface Calendar {
  end_date: string;
  friday: number;
  monday: number;
  saturday: number;
  service_id: string;
  start_date: string;
  sunday: number;
  thursday: number;
  tuesday: number;
  wednesday: number;
}

export interface CalendarAttributes {
  service_description: string;
  service_id: string | null;
}

export interface CalendarDates {
  date: string;
  exception_type: number;
  holiday_name: string | null;
  service_id: string;
}

export interface Deadheads {
  block_id: string;
  deadhead_id: string;
  from_deadhead_id: string | null;
  from_trip_id: string | null;
  service_id: string;
  shape_id: string | null;
  to_deadhead_id: string | null;
  to_trip_id: string | null;
}

export interface DeadheadTimes {
  arrival_time: string;
  deadhead_id: string;
  departure_time: string;
  location_sequence: number;
  ops_location_id: string | null;
  shape_dist_traveled: number | null;
  stop_id: string | null;
}

export interface Devices {
  device_id: string;
  device_location: string | null;
  device_model: string | null;
  device_type: string | null;
  device_vendor: string | null;
  stop_id: string | null;
  train_car_id: string | null;
  vehicle_id: string | null;
}

export interface Directions {
  direction: string;
  direction_id: number | null;
  route_id: string;
}

export interface FareAttributes {
  agency_id: string | null;
  currency_type: string;
  fare_id: string;
  payment_method: number;
  price: number;
  transfer_duration: number | null;
  transfers: number | null;
}

export interface FareLegRules {
  fare_product_id: string;
  from_area_id: string | null;
  from_timeframe_group_id: string | null;
  leg_group_id: string | null;
  network_id: string | null;
  rule_priority: number | null;
  to_area_id: string | null;
  to_timeframe_group_id: string | null;
}

export interface FareMedia {
  fare_media_id: string;
  fare_media_name: string | null;
  fare_media_type: number;
}

export interface FareProducts {
  amount: number;
  currency: string;
  fare_media_id: string | null;
  fare_product_id: string;
  fare_product_name: string | null;
  rider_category_id: string | null;
}

export interface FareRules {
  contains_id: string | null;
  destination_id: string | null;
  fare_id: string;
  origin_id: string | null;
  route_id: string | null;
}

export interface FareTransactions {
  amount: number;
  balance: number | null;
  currency_type: string | null;
  device_id: string | null;
  event_timestamp: string;
  fare_action: string;
  fare_capped: string;
  fare_id: string | null;
  fare_media_id: string | null;
  fare_period: string | null;
  fare_product: string | null;
  location_ping_id: string | null;
  num_riders: number | null;
  pattern_id: string | null;
  rider_category: string | null;
  scheduled_stop_sequence: number | null;
  service_date: string;
  stop_id: string | null;
  token_id: string | null;
  transaction_id: string;
  trip_id_performed: string | null;
  trip_id_scheduled: string | null;
  trip_stop_sequence: number | null;
  vehicle_id: string | null;
}

export interface FareTransferRules {
  duration_limit: number | null;
  duration_limit_type: number | null;
  fare_product_id: string | null;
  fare_transfer_type: number;
  from_leg_group_id: string | null;
  to_leg_group_id: string | null;
  transfer_count: number | null;
}

export interface FeedInfo {
  default_lang: string | null;
  feed_contact_email: string | null;
  feed_contact_url: string | null;
  feed_end_date: string | null;
  feed_lang: string;
  feed_publisher_name: string;
  feed_publisher_url: string;
  feed_start_date: string | null;
  feed_version: string | null;
}

export interface Frequencies {
  end_time: string;
  exact_times: number | null;
  headway_secs: number;
  start_time: string;
  trip_id: string;
}

export interface Levels {
  level_id: string;
  level_index: number;
  level_name: string | null;
}

export interface LocationGroups {
  location_group_id: string | null;
  location_group_name: string | null;
}

export interface LocationGroupStops {
  location_group_id: string;
  stop_id: string;
}

export interface Locations {
  geojson: string | null;
}

export interface Networks {
  network_id: string;
  network_name: string | null;
}

export interface Operators {
  operator_id: string;
}

export interface OpsLocations {
  ops_location_code: string | null;
  ops_location_desc: string | null;
  ops_location_id: string;
  ops_location_lat: number;
  ops_location_lon: number;
  ops_location_name: string;
}

export interface PassengerEvents {
  device_id: string | null;
  event_count: number | null;
  event_timestamp: string;
  event_type: string;
  location_ping_id: string | null;
  passenger_event_id: string;
  pattern_id: string | null;
  scheduled_stop_sequence: number | null;
  service_date: string;
  stop_id: string | null;
  train_car_id: string | null;
  trip_id_performed: string | null;
  trip_id_scheduled: string | null;
  trip_stop_sequence: number | null;
  vehicle_id: string;
}

export interface Pathways {
  from_stop_id: string;
  is_bidirectional: number;
  length: number | null;
  max_slope: number | null;
  min_width: number | null;
  pathway_id: string;
  pathway_mode: number;
  reversed_signposted_as: string | null;
  signposted_as: string | null;
  stair_count: number | null;
  to_stop_id: string;
  traversal_time: number | null;
}

export interface RideFeedInfo {
  default_currency_type: string | null;
  gtfs_feed_date: string | null;
  ride_end_date: string | null;
  ride_feed_version: string | null;
  ride_files: number;
  ride_start_date: string | null;
}

export interface RiderCategories {
  eligibility_url: string | null;
  is_default_fare_category: number | null;
  rider_category_id: string;
  rider_category_name: string;
}

export interface Ridership {
  agency_id: string | null;
  direction_id: number | null;
  friday: number | null;
  monday: number | null;
  ridership_end_date: string | null;
  ridership_end_time: string | null;
  ridership_start_date: string | null;
  ridership_start_time: string | null;
  route_id: string | null;
  saturday: number | null;
  service_id: string | null;
  stop_id: string | null;
  sunday: number | null;
  thursday: number | null;
  total_alightings: number;
  total_boardings: number;
  trip_id: string | null;
  tuesday: number | null;
  wednesday: number | null;
}

export interface RiderTrip {
  accompanying_device: number | null;
  agency_id: string | null;
  alighting_stop_id: string | null;
  alighting_stop_sequence: number | null;
  alighting_time: string | null;
  boarding_stop_id: string | null;
  boarding_stop_sequence: number | null;
  boarding_time: string | null;
  fare_media: number | null;
  fare_paid: number | null;
  rider_id: string | null;
  rider_type: number | null;
  rider_type_description: string | null;
  service_date: string | null;
  transaction_type: number | null;
  transfer_status: number | null;
  trip_id: string | null;
}

export interface RouteAttributes {
  category: number;
  route_id: string | null;
  running_way: number;
  subcategory: number;
}

export interface RouteNetworks {
  network_id: string;
  route_id: string | null;
}

export interface Routes {
  agency_id: string | null;
  cemv_support: number | null;
  continuous_drop_off: number | null;
  continuous_pickup: number | null;
  network_id: string | null;
  route_color: string | null;
  route_desc: string | null;
  route_id: string;
  route_long_name: string | null;
  route_short_name: string | null;
  route_sort_order: number | null;
  route_text_color: string | null;
  route_type: number;
  route_url: string | null;
}

export interface RunEvent {
  event_duration: number;
  event_from_location_id: string | null;
  event_from_location_type: number | null;
  event_name: string | null;
  event_time: string;
  event_to_location_id: string | null;
  event_to_location_type: number | null;
  event_type: number;
  piece_id: string;
  run_event_id: string;
}

export interface RunsPieces {
  end_trip_id: string;
  end_trip_position: number | null;
  end_type: number;
  piece_id: string;
  run_id: string;
  start_trip_id: string;
  start_trip_position: number | null;
  start_type: number;
}

export interface ServiceAlertInformedEntities {
  alert_id: string;
  created_timestamp: number;
  direction_id: number | null;
  expiration_timestamp: number;
  route_id: string | null;
  route_type: number | null;
  stop_id: string | null;
  trip_id: string | null;
}

export interface ServiceAlerts {
  active_period: string | null;
  cause: string | null;
  created_timestamp: number;
  description_text: string;
  effect: string | null;
  end_time: string;
  expiration_timestamp: number;
  header_text: string;
  id: string;
  severity_level: string | null;
  start_time: string;
  tts_description_text: string | null;
  tts_header_text: string | null;
  url: string | null;
}

export interface Shapes {
  shape_dist_traveled: number | null;
  shape_id: string;
  shape_pt_lat: number;
  shape_pt_lon: number;
  shape_pt_sequence: number;
}

export interface StationActivities {
  bike_entries: number | null;
  bike_exits: number | null;
  number_of_transactions: number | null;
  ramp_entries: number | null;
  ramp_exits: number | null;
  service_date: string;
  stop_id: string;
  time_period_category: string | null;
  time_period_end: string;
  time_period_start: string;
  total_entries: number | null;
  total_exits: number | null;
}

export interface StopAreas {
  area_id: string;
  stop_id: string;
}

export interface StopAttributes {
  accessibility_id: number | null;
  cardinal_direction: string | null;
  relative_position: string | null;
  stop_city: string | null;
  stop_id: string;
}

export interface Stops {
  level_id: string | null;
  location_type: number | null;
  parent_station: string | null;
  platform_code: string | null;
  stop_access: number | null;
  stop_code: string | null;
  stop_desc: string | null;
  stop_id: string;
  stop_lat: number | null;
  stop_lon: number | null;
  stop_name: string | null;
  stop_timezone: string | null;
  stop_url: string | null;
  tts_stop_name: string | null;
  wheelchair_boarding: number | null;
  zone_id: string | null;
}

export interface StopTimes {
  arrival_time: string | null;
  continuous_drop_off: number | null;
  continuous_pickup: number | null;
  departure_time: string | null;
  drop_off_booking_rule_id: string | null;
  drop_off_type: number | null;
  location_group_id: string | null;
  location_id: string | null;
  pickup_booking_rule_id: string | null;
  pickup_type: number | null;
  shape_dist_traveled: number | null;
  start_pickup_drop_off_window: string | null;
  stop_headsign: string | null;
  stop_id: string;
  stop_sequence: number;
  timepoint: number | null;
  trip_id: string;
}

export interface StopTimeUpdates {
  arrival_delay: number | null;
  arrival_timestamp: string | null;
  created_timestamp: number;
  departure_delay: number | null;
  departure_timestamp: string | null;
  direction_id: number | null;
  expiration_timestamp: number;
  route_id: string | null;
  schedule_relationship: string | null;
  stop_id: string | null;
  stop_sequence: number | null;
  trip_id: string | null;
  trip_start_time: string | null;
}

export interface StopVisits {
  actual_arrival_time: string | null;
  actual_departure_time: string | null;
  alighting_1: number | null;
  alighting_2: number | null;
  bike_load: number | null;
  bike_rack_deployed: string | null;
  boarding_1: number | null;
  boarding_2: number | null;
  departure_load: number | null;
  distance: number | null;
  door_close: string | null;
  door_open: string | null;
  door_status: string | null;
  dwell: number | null;
  kneel_deployed_time: number | null;
  lift_deployed_time: number | null;
  number_of_transactions: number | null;
  pattern_id: string | null;
  ramp_deployed_time: string | null;
  ramp_failure: string | null;
  revenue: number | null;
  schedule_arrival_time: string | null;
  schedule_departure_time: string | null;
  schedule_relationship: string | null;
  scheduled_stop_sequence: number | null;
  service_date: string;
  stop_id: string | null;
  timepoint: string | null;
  trip_id_performed: string;
  trip_stop_sequence: number;
  vehicle_id: string | null;
}

export interface Test {
  id: number | null;
  name: string | null;
}

export interface Timeframes {
  end_time: string | null;
  service_id: string;
  start_time: string | null;
  timeframe_group_id: string | null;
}

export interface TimetableNotes {
  note: string;
  note_id: string;
  symbol: string | null;
}

export interface TimetableNotesReferences {
  note_id: string;
  route_id: string | null;
  show_on_stoptime: number | null;
  stop_id: string | null;
  stop_sequence: number | null;
  timetable_id: string | null;
  trip_id: string | null;
}

export interface TimetablePages {
  filename: string | null;
  timetable_page_id: string;
  timetable_page_label: string | null;
}

export interface Timetables {
  direction_id: number | null;
  direction_name: string | null;
  end_date: string | null;
  end_time: string | null;
  friday: number;
  include_exceptions: number | null;
  monday: number;
  orientation: string | null;
  route_id: string;
  saturday: number;
  service_notes: string | null;
  show_trip_continuation: number | null;
  start_date: string | null;
  start_time: string | null;
  sunday: number;
  thursday: number;
  timetable_id: string;
  timetable_label: string | null;
  timetable_page_id: string | null;
  timetable_sequence: number | null;
  tuesday: number;
  wednesday: number;
}

export interface TimetableStopOrder {
  stop_id: string;
  stop_sequence: number;
  timetable_id: string;
}

export interface TrainCars {
  bike_rack: string | null;
  capacity_bike: number | null;
  capacity_seated: number | null;
  capacity_standing: number | null;
  capacity_wheelchair: number | null;
  facility_name: string | null;
  model_name: string | null;
  train_car_id: string;
  train_car_type: string | null;
}

export interface Transfers {
  from_route_id: string | null;
  from_stop_id: string | null;
  from_trip_id: string | null;
  min_transfer_time: number | null;
  to_route_id: string | null;
  to_stop_id: string | null;
  to_trip_id: string | null;
  transfer_type: number | null;
}

export interface Translations {
  field_name: string;
  field_value: string | null;
  language: string;
  record_id: string | null;
  record_sub_id: string | null;
  table_name: string;
  translation: string;
}

export interface TripCapacity {
  agency_id: string | null;
  bike_capacity: number | null;
  seated_capacity: number | null;
  service_date: string | null;
  standing_capacity: number | null;
  trip_id: string | null;
  vehicle_description: string | null;
  wheelchair_capacity: number | null;
}

export interface Trips {
  bikes_allowed: number | null;
  block_id: string | null;
  cars_allowed: number | null;
  direction_id: number | null;
  route_id: string;
  safe_duration_factor: number | null;
  safe_duration_offset: number | null;
  service_id: string;
  shape_id: string | null;
  trip_headsign: string | null;
  trip_id: string;
  trip_short_name: string | null;
  wheelchair_accessible: number | null;
}

export interface TripsDatedVehicleJourney {
  dated_vehicle_journey_gid: string;
  journey_number: number | null;
  operating_day_date: string;
  trip_id: string;
}

export interface TripsPerformed {
  actual_trip_end: string | null;
  actual_trip_start: string | null;
  block_id: string | null;
  direction_id: number | null;
  ntd_mode: string | null;
  operator_id: string | null;
  pattern_id: string | null;
  route_id: string | null;
  route_type: string | null;
  route_type_agency: string | null;
  schedule_relationship: string | null;
  schedule_trip_end: string | null;
  schedule_trip_start: string | null;
  service_date: string;
  shape_id: string | null;
  trip_end_stop_id: string | null;
  trip_id_performed: string;
  trip_id_scheduled: string | null;
  trip_start_stop_id: string | null;
  trip_type: string | null;
  vehicle_id: string;
}

export interface TripUpdates {
  created_timestamp: number;
  direction_id: number | null;
  expiration_timestamp: number;
  id: string;
  route_id: string | null;
  schedule_relationship: string | null;
  start_date: string | null;
  timestamp: string | null;
  trip_id: string | null;
  trip_start_time: string | null;
  vehicle_id: string | null;
}

export interface VehicleLocations {
  current_status: string | null;
  device_id: string | null;
  event_timestamp: string;
  gps_quality: string | null;
  heading: number | null;
  headway_deviation: number | null;
  latitude: number | null;
  location_ping_id: string;
  longitude: number | null;
  odometer: number | null;
  pattern_id: string | null;
  schedule_deviation: number | null;
  schedule_relationship: string | null;
  scheduled_stop_sequence: number | null;
  service_date: string | null;
  speed: number | null;
  stop_id: string | null;
  trip_id_performed: string | null;
  trip_id_scheduled: string | null;
  trip_stop_sequence: number | null;
  trip_type: string | null;
  vehicle_id: string;
}

export interface VehiclePositions {
  bearing: number | null;
  congestion_level: string | null;
  created_timestamp: number;
  current_stop_sequence: number | null;
  expiration_timestamp: number;
  id: string;
  latitude: number | null;
  longitude: number | null;
  occupancy_percentage: number | null;
  occupancy_status: string | null;
  speed: number | null;
  timestamp: string | null;
  trip_id: string | null;
  trip_start_date: string | null;
  trip_start_time: string | null;
  vehicle_id: string | null;
  vehicle_label: string | null;
  vehicle_license_plate: string | null;
  vehicle_stop_status: string | null;
  vehicle_wheelchair_accessible: string | null;
}

export interface Vehicles {
  bike_rack: string | null;
  capacity_bike: number | null;
  capacity_seated: number | null;
  capacity_standing: number | null;
  capacity_wheelchair: number | null;
  facility_name: string | null;
  model_name: string | null;
  vehicle_end: string | null;
  vehicle_id: string;
  vehicle_start: string | null;
}

export interface VehicleTrainCars {
  operator_id: string | null;
  train_car_id: string;
  train_car_order: number | null;
  vehicle_id: string;
}

export interface DB {
  agency: Agency;
  areas: Areas;
  attributions: Attributions;
  board_alight: BoardAlight;
  booking_rules: BookingRules;
  calendar: Calendar;
  calendar_attributes: CalendarAttributes;
  calendar_dates: CalendarDates;
  deadhead_times: DeadheadTimes;
  deadheads: Deadheads;
  devices: Devices;
  directions: Directions;
  fare_attributes: FareAttributes;
  fare_leg_rules: FareLegRules;
  fare_media: FareMedia;
  fare_products: FareProducts;
  fare_rules: FareRules;
  fare_transactions: FareTransactions;
  fare_transfer_rules: FareTransferRules;
  feed_info: FeedInfo;
  frequencies: Frequencies;
  levels: Levels;
  location_group_stops: LocationGroupStops;
  location_groups: LocationGroups;
  locations: Locations;
  networks: Networks;
  operators: Operators;
  ops_locations: OpsLocations;
  passenger_events: PassengerEvents;
  pathways: Pathways;
  ride_feed_info: RideFeedInfo;
  rider_categories: RiderCategories;
  rider_trip: RiderTrip;
  ridership: Ridership;
  route_attributes: RouteAttributes;
  route_networks: RouteNetworks;
  routes: Routes;
  run_event: RunEvent;
  runs_pieces: RunsPieces;
  service_alert_informed_entities: ServiceAlertInformedEntities;
  service_alerts: ServiceAlerts;
  shapes: Shapes;
  station_activities: StationActivities;
  stop_areas: StopAreas;
  stop_attributes: StopAttributes;
  stop_time_updates: StopTimeUpdates;
  stop_times: StopTimes;
  stop_visits: StopVisits;
  stops: Stops;
  test: Test;
  timeframes: Timeframes;
  timetable_notes: TimetableNotes;
  timetable_notes_references: TimetableNotesReferences;
  timetable_pages: TimetablePages;
  timetable_stop_order: TimetableStopOrder;
  timetables: Timetables;
  train_cars: TrainCars;
  transfers: Transfers;
  translations: Translations;
  trip_capacity: TripCapacity;
  trip_updates: TripUpdates;
  trips: Trips;
  trips_dated_vehicle_journey: TripsDatedVehicleJourney;
  trips_performed: TripsPerformed;
  vehicle_locations: VehicleLocations;
  vehicle_positions: VehiclePositions;
  vehicle_train_cars: VehicleTrainCars;
  vehicles: Vehicles;
}
